[package]
name = "nautilus_model"
version = "0.1.0"
authors = ["Nautech Systems <info@nautechsystems.io>"]
edition = "2021"

[lib]
name = "nautilus_model"
crate-type = ["rlib", "staticlib"]

[dependencies]
cbindgen = "^0.20.0"
chrono = "^0.4.19"
rust_decimal = "^1.21.0"

nautilus_core = { path = "../core" }

[build-dependencies]
cbindgen = "^0.20.0"
