[package]
name = "nautilus_core"
version = "0.1.0"
authors = ["Nautech Systems <info@nautechsystems.io>"]
edition = "2018"

[lib]
name = "nautilus_core"
crate-type = ["rlib", "staticlib"]

[dependencies]
cbindgen = "0.17.0"
uuid = { version = "0.8.2", features = ["v4"] }

[build-dependencies]
cbindgen = "0.17.0"