[workspace]
resolver = "2"

members = [
    "src/core",
    "src/model",
]

# Debug symbols end up chewing up several GB of disk space, so better to just
# disable them.
[profile.dev]
debug = false
[profile.test]
debug = false
